version: "1.0"

stages:
  - init
  - build
  - publish
  - prepare_deploy
  - deploy

steps:
  main_clone:
    stage: init
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: github

  set_common_vars:
    stage: init
    image: alpine:latest
    commands:
      - cf_export INGRESS_CLASS="internal-ingress"
      - cf_export OWNER_TEAM="internal"
      - cf_export HTTP_SERVER_LISTEN_ADDR="0.0.0.0:8080"
      - cf_export CERVED_OAUTH_BASE_URL="https://cas.cerved.com"
      - cf_export CERVED_API_BASE_URL="https://api.cerved.com"

  set_production_vars:
    stage: init
    image: alpine:latest
    commands:
      - cf_export K8S_CLUSTER="credimi-prod"
      - cf_export EKS_ACM_ARN=${{PROD_EKS_ACM_ARN}}
      - cf_export NAMESPACE="prod"
      - cf_export HOST="{{CF_REPO_NAME}}.private.bancacfplus.it"
    when:
      branch:
        only:
          - /^release-[0-9]{8}[a-z]*$/

  set_staging_vars:
    stage: init
    image: alpine:latest
    commands:
      - cf_export K8S_CLUSTER="credimi-qa"
      - cf_export EKS_ACM_ARN=${{QA_EKS_ACM_ARN}}
      - cf_export NAMESPACE="${{CF_BRANCH_TAG_NORMALIZED}}"
      - cf_export HOST="${{CF_BRANCH_TAG_NORMALIZED}}-{{CF_REPO_NAME}}.qa.private.bancacfplus.it"
    when: &is_not_release
      branch:
        ignore:
          - /^release-[0-9]{8}[a-z]*$/

  check_docker_image_existence:
    stage: build
    type: freestyle
    image: credimi/codefresh-verify-image:773ff8a
    environment:
      - IMAGE_NAME=${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}

  build_app_image:
    stage: build
    type: build
    dockerfile: Dockerfile
    target: runtime
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_SHORT_REVISION}}
    no_cache: false
    no_cf_cache: false
    disable_push: true
    when: &image_not_already_built
      condition:
        all:
          imageExists: "${{IMAGE_EXISTS}} == false"

  build_tests_image:
    stage: build
    type: build
    dockerfile: Dockerfile
    target: builder
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}-tests
    tag: ${{CF_SHORT_REVISION}}
    disable_push: true
    when: *image_not_already_built

  run_tests:
    stage: build
    type: composition
    composition: 'docker-compose.yml'
    composition_candidates:
      run_tests:
        image: ${{build_tests_image}}
        environment:
          S3_DRY_RUN: true
          CERVED_API_BASE_URL: http://mockoon:3001
          CERVED_OAUTH_BASE_URL: http://mockoon:3001
          CERVED_OAUTH_USERNAME: username
          CERVED_OAUTH_PASSWORD: PASSWORD
          QRP_BUCKET_NAME: qrp-bucket-test
        command: sh -c "sleep 5s && cargo test --release --no-fail-fast"
        depends_on:
          - mockoon
    when: *image_not_already_built

  publish_images:
    stage: publish
    type: parallel
    steps:
      publish_app_image:
        type: push
        candidate: ${{build_app_image}}
        tags:
          - ${{CF_SHORT_REVISION}}
          - ${{CF_BRANCH_TAG_NORMALIZED}}
    when: *image_not_already_built

  create_namespace:
    stage: prepare_deploy
    image: credimi/codefresh-deploy:${{CODEFRESH_DEPLOY_VERSION}}
    environment:
      - YAML_PATH=./k8s/namespace.yaml
    when: *is_not_release

  copy_secrets:
    stage: prepare_deploy
    image: credimi/codefresh-copy-secrets:${{CODEFRESH_DEPLOY_VERSION}}
    environment:
      - OTHER_SECRETS=${{CF_REPO_NAME}}-secrets
    when: *is_not_release

  deploy_app:
    stage: deploy
    image: credimi/codefresh-deploy:${{CODEFRESH_DEPLOY_VERSION}}
    environment:
      - YAML_PATH=./k8s/deployment.yaml
