-- Your SQL goes here
CREATE TABLE flags (
  id SERIAL PRIMARY KEY,
  creation_timestamp TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  update_timestamp TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  flag BOOLEAN NOT NULL
)